import fashion from "@/assets/work-fashion.jpg";
import food from "@/assets/work-food.jpg";
import realestate from "@/assets/work-realestate.jpg";
import branding from "@/assets/work-branding.jpg";
import product from "@/assets/work-product.jpg";
import corporate from "@/assets/work-corporate.jpg";
import studio from "@/assets/studio.jpg";
import hero from "@/assets/hero.jpg";

import type { Project } from "./site";

/** PLACEHOLDER imagery — replace each `image` with the real project asset. */
export const projects: Project[] = [
  {
    slug: "kora-label-ss-campaign",
    title: "Spring/Summer Lookbook",
    client: "Kora Label",
    category: "Photography",
    industry: "Fashion",
    ratio: "portrait",
    image: fashion,
    alt: "Fashion photography services — editorial lookbook portrait for a Kolkata clothing label",
    challenge: "A new label needed a campaign that read as premium without a premium budget.",
    approach: "One studio day, two lighting setups, tight art direction and a warm grade tuned to the fabric palette.",
    result: "42 finished frames covering e-commerce, paid social and print — enough for two full seasons of content.",
    outcome: "+40% engagement in 30 days",
    hasBeforeAfter: true,
  },
  {
    slug: "bistro-nine-menu",
    title: "Signature Menu Shoot",
    client: "Bistro Nine",
    category: "Photography",
    industry: "Food",
    ratio: "landscape",
    image: food,
    alt: "Restaurant photography services — plated signature dish shot with cinematic warm lighting",
    challenge: "Delivery-app listings were underperforming against neighbouring restaurants.",
    approach: "Rebuilt the menu hierarchy visually, shooting hero dishes with controlled warm light and real plating.",
    result: "A 60-image library covering apps, menus and social, plus a reusable shot-list template.",
    outcome: "+28% delivery order rate",
  },
  {
    slug: "silverline-walkthrough",
    title: "Residence Walkthrough Film",
    client: "Silverline Realty",
    category: "Videography",
    industry: "Real Estate",
    ratio: "landscape",
    image: realestate,
    alt: "Real estate photography and videography — luxury living room interior at dusk",
    challenge: "Buyers were dropping off before booking a site visit.",
    approach: "A 90-second gimbal walkthrough with dusk lighting, plus vertical cutdowns for paid social.",
    result: "One master film, three cutdowns and 30 interior stills from a single two-day shoot.",
    outcome: "+35% site-visit enquiries",
    isVideo: true,
  },
  {
    slug: "lumen-identity",
    title: "Identity System",
    client: "Lumen Studios",
    category: "Branding",
    industry: "Corporate",
    ratio: "portrait",
    image: branding,
    alt: "Branding agency work — cream stationery system with orange accents on charcoal",
    challenge: "Three sub-brands, no shared visual language, inconsistent decks.",
    approach: "Positioning workshop, one responsive logo suite, and a documented colour and type system.",
    result: "Full brand book, templated deck system and social toolkit adopted across all teams.",
    hasBeforeAfter: true,
  },
  {
    slug: "nuvo-product-launch",
    title: "Product Launch Campaign",
    client: "Nuvo Care",
    category: "Social Media",
    industry: "Retail",
    ratio: "landscape",
    image: product,
    alt: "Commercial product photography — skincare bottles lit with warm orange gel on dark background",
    challenge: "A launch window of three weeks and no existing creative assets.",
    approach: "Batched studio day producing stills, stop-motion and nine-by-sixteen hooks in one pass.",
    result: "24 posts, six reels and a full paid-ad creative set delivered inside 12 days.",
    outcome: "2.1M views in launch month",
  },
  {
    slug: "meridian-corporate-film",
    title: "Company Profile Film",
    client: "Meridian Industries",
    category: "Videography",
    industry: "Corporate",
    ratio: "portrait",
    image: corporate,
    alt: "Corporate videography services — camera operator filming an executive interview in an office",
    challenge: "Export buyers had no way to assess capability remotely.",
    approach: "Leadership interviews plus plant b-roll, cut into a four-minute profile with subtitled versions.",
    result: "One flagship film, a 60-second sales cut and a multilingual subtitle set.",
    outcome: "Used in every export pitch since",
    isVideo: true,
  },
  {
    slug: "atria-brand-films",
    title: "Hospitality Brand Films",
    client: "Atria Hotels",
    category: "Videography",
    industry: "Hospitality",
    ratio: "landscape",
    image: hero,
    alt: "Creative production agency on set — film crew with cinema cameras under warm lighting",
    challenge: "OTA dependency was eating into margins.",
    approach: "A guest-journey film series shot across three properties, designed to drive direct bookings.",
    result: "Six property films plus a stills library covering rooms, dining and events.",
    outcome: "+18% direct bookings",
    isVideo: true,
  },
  {
    slug: "vertex-social-engine",
    title: "Always-On Social Engine",
    client: "Vertex Retail",
    category: "Social Media",
    industry: "Retail",
    ratio: "portrait",
    image: studio,
    alt: "Content creation team editing social media video content in a dark studio suite",
    challenge: "Posting was inconsistent and mostly reactive.",
    approach: "Monthly calendar with one batched shoot day and a performance review loop.",
    result: "30 posts per month sustained for six months with a rising save-and-share rate.",
    outcome: "3.4x saves per post",
  },
  {
    slug: "kora-motion-toolkit",
    title: "Animated Brand Toolkit",
    client: "Kora Label",
    category: "Graphic Design",
    industry: "Fashion",
    ratio: "landscape",
    image: product,
    alt: "Motion graphics and graphic design work — animated brand toolkit frames",
    challenge: "Every campaign was designed from scratch, slowly.",
    approach: "Built a key-visual system with animated logo stings and templated post layouts.",
    result: "A reusable design and motion kit that cut campaign turnaround by half.",
  },
  {
    slug: "bistro-nine-ambience",
    title: "Ambience Short Film",
    client: "Bistro Nine",
    category: "Videography",
    industry: "Food",
    ratio: "portrait",
    image: food,
    alt: "Restaurant videography — moody ambience film still of a plated dish",
    challenge: "The room felt special in person and flat online.",
    approach: "Low-light cinematic coverage of service, using practical warmth instead of added light.",
    result: "A 45-second ambience film plus 12 vertical cutdowns for reels and stories.",
  },
  {
    slug: "silverline-print-campaign",
    title: "Launch Print Campaign",
    client: "Silverline Realty",
    category: "Graphic Design",
    industry: "Real Estate",
    ratio: "landscape",
    image: realestate,
    alt: "Graphic design services — real estate launch print campaign layout",
    challenge: "Print, hoarding and digital versions were drifting apart visually.",
    approach: "One key visual, systemised across every format with a documented crop logic.",
    result: "Print-ready and digital sets for eight placements, delivered in one week.",
  },
  {
    slug: "lumen-founder-portraits",
    title: "Leadership Portraits",
    client: "Lumen Studios",
    category: "Photography",
    industry: "Corporate",
    ratio: "portrait",
    image: corporate,
    alt: "Corporate photography services — leadership portrait session in a modern office",
    challenge: "Inconsistent headshots weakened an otherwise sharp brand.",
    approach: "One repeatable lighting recipe so future hires match the existing set exactly.",
    result: "Portraits for 14 team members plus a documented setup for future sessions.",
  },
  {
    slug: "atria-suite-stills",
    title: "Suite & Dining Stills",
    client: "Atria Hotels",
    category: "Photography",
    industry: "Hospitality",
    ratio: "landscape",
    image: realestate,
    alt: "Hospitality photography services — hotel suite interior with warm evening light",
    challenge: "Legacy images undersold a freshly renovated property.",
    approach: "Dusk-window scheduling and careful styling in every room category.",
    result: "48 images across suites, dining and common areas, versioned for OTA and web.",
  },
  {
    slug: "nuvo-explainer",
    title: "Product Explainer",
    client: "Nuvo Care",
    category: "Graphic Design",
    industry: "Healthcare",
    ratio: "portrait",
    image: branding,
    alt: "Motion graphics explainer design frames for a healthcare product",
    challenge: "A technical formulation nobody could explain in one line.",
    approach: "A 50-second animated explainer built from the existing design system.",
    result: "One explainer, three social cutdowns and a reusable animation library.",
    outcome: "76% average completion rate",
  },
  {
    slug: "vertex-campaign-stills",
    title: "Seasonal Campaign Stills",
    client: "Vertex Retail",
    category: "Photography",
    industry: "Retail",
    ratio: "landscape",
    image: product,
    alt: "Commercial photography services — seasonal retail product campaign stills",
    challenge: "A 40-SKU catalogue refresh with a fixed launch date.",
    approach: "Assembly-line studio workflow with locked lighting and tethered review.",
    result: "All 40 SKUs plus 10 lifestyle frames shot and delivered in four days.",
  },
  {
    slug: "meridian-brand-refresh",
    title: "Brand Refresh",
    client: "Meridian Industries",
    category: "Branding",
    industry: "Manufacturing",
    ratio: "portrait",
    image: branding,
    alt: "Brand identity refresh design for a manufacturing company",
    challenge: "A 30-year-old identity that no longer matched the company's scale.",
    approach: "Evolution over revolution: kept the equity, modernised the system.",
    result: "New mark, palette, signage spec and a practical 32-page brand book.",
    hasBeforeAfter: true,
  },
];
